### ISSUE TITLE
Bug with dymo web service

### ISSUE THREAD

**Issue by lolek1996** [apenab/react-dymo#14]
Hi there, I have installed the last version of the dymo web service on windows later on I have installed this package using the instructions on the Readme.md. I can't perform any operation with this library and I get errors in the requests. I'm using the latest version of the dymo web service and the latest version of this package

**Comment by apenab** [comment]
Thanks for the report I will review soon.

**Comment by apenab** [comment]
@lolek1996 I can't reproduce this bug, can you give me more details?

**Comment by juancamilorivas** [comment]
i got this error when i run start, please could u help me

C:/Users/bogot/node_modules/react-dymo-hooks/dist/index.modern.js
Module not found: Can't resolve 'react' in 'C:\Users\bogot\node_modules\react-dymo-hooks\dist'
